services:
  - type: web
    name: praf-pos
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
